ALTER TABLE folders
ADD COLUMN IF NOT EXISTS is_paid BOOLEAN DEFAULT FALSE;

ALTER TABLE folders
ADD COLUMN IF NOT EXISTS price_inr INTEGER DEFAULT 0;

ALTER TABLE folders
ADD COLUMN IF NOT EXISTS discount_percent INTEGER DEFAULT 0;

ALTER TABLE folders
ADD COLUMN IF NOT EXISTS sale_price_inr INTEGER DEFAULT 0;
