-- Superseded by security_final.sql.
--
-- Do not run this file by itself for production. It used to contain permissive
-- setup policies for early admin testing. For launch, run:
--
--   supabase/security_final.sql
--
-- That file keeps catalog metadata readable, blocks direct browser writes,
-- protects paid questions, and limits reports/payments/student data by owner
-- or admin role.
